baseURL = 'http://qt1b.github.io/'
languageCode = 'en-us'
title = "qt1b's personal page"
theme = ["PaperMod", "gokarna","hello-friend-ng","terminal"] # "terminal" #"gokarna"

[menus]
  [[menus.main]]
    name = 'CTF Writeups'
    pageRef = '/writeups/asis/2024/detic'
    weight = 100
  [[menus.main]]
    name = 'misc'
    pageRef = '/writeups/pwn'
    parent = 'CTF Writeups'
    weight = 3
  [[menus.main]]
    name = 'misc'
    pageRef = '/writeups/rev'
    parent = 'CTF Writeups'
    weight = 2
  [[menus.main]]
    name = 'misc'
    pageRef = '/writeups/misc'
    parent = 'CTF Writeups'
    weight = 1


# used to center / redimension images in specific cases
[markup.goldmark.renderer]
unsafe = true
